# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4665068cc21a385e58373280eb33fefe121697d12b1005bed4bd0fa909de3fccf09fe21270b2b169712e8ae5f6e2e21a50453d352708f99a5dc589dffa1316ef

test:
  secret_key_base: a5aa0f7226dbe085b7ff29c159d389dd88e00a738154ad14758e70b7b6a98d23fbbb34cce9420cd49d84ecc9e0d8dd92f200e4cb6e61a8d544edf21416adabe9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
